fix: pooling card amount, closes #1150
hirosystems/desktop-wallet pull request #1188
Opened 2023-04-14 09:08 UTC by kyranjamie

We used to get a value back from the stacking library that we no longer do (defaults to 0).  Rather than showing the amount that the user allowed to delegate, we show the amount currently locked.

2023-04-14 11:32 UTC, alter-eggo approved these changes

2023-04-15 07:28 UTC, friedger commented
Locked balance does not look correct for delegation card.

2023-04-15 07:47 UTC, friedger requested changes
The error is in https://github.com/hirosystems/desktop-wallet/blob/43fa4bd4d1b9945892df08219b5c25b3d746043a/app/hooks/use-delegation-status.ts#L41

where the type of UIntCV.value is assumed to be a BN instance, but it is a bigint

2023-04-15 07:51 UTC, markmhx commented
@friedger you're saying we do still get the proper "delegated amount" from the API, just need to fix a syntax error?

2023-04-15 07:59 UTC, friedger commented
@markmhx Correct

2023-04-15 19:21 UTC, markmhx commented
@kyranjamie let's get a fix in place with @friedger's guidance above and keep the meaning of "pooled" here consistent? If we weren't to have this data point, we'd need to change the label as well to prevent confusion (e.g. to "You have locked" or similar)

2023-04-17 08:11 UTC, kyranjamie commented
Thanks @friedger, updated

2023-04-17 13:35 UTC, fbwoolf approved these changes

2023-04-17 13:36 UTC, merged